[package]
name = "skia_test"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exr = "0.9.0"
lazy_static = "1.4.0"
skia-safe = "0.36.0"
